name: build_pipe
description: The pipline to build & publish Flutter apps for different target platforms
version: 0.2.5
repository: https://github.com/vieolo/flutter_build_pipe

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  yaml: ^3.1.3
  path: ^1.9.1
  crypto: ^3.0.6
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0

executables:
  build:
  publish:
